# Generated by Django 5.0.1 on 2024-03-04 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='His bare hands', max_length=30)),
                ('is_ranged', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(default='Body part', max_length=15)),
                ('damage_type', models.CharField(default='Physical', max_length=15)),
                ('physical_description', models.CharField(default="It's using his hands", max_length=100)),
                ('image', models.ImageField(default='weapon/images/default.png', upload_to='weapon/images/')),
                ('damage', models.IntegerField(default=10)),
                ('range', models.IntegerField(default=1)),
                ('durability', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT_MONSTER', max_length=30)),
                ('monster_race', models.CharField(default='Goblin', max_length=30)),
                ('monster_class', models.CharField(default='Warrior', max_length=30)),
                ('physical_description', models.CharField(default='Green goblin, small, with no weapon', max_length=100)),
                ('max_health', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('physical_resistance', models.IntegerField(default=10)),
                ('magical_resistance', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('exp_drop', models.IntegerField(default=10)),
                ('x', models.IntegerField(default=2)),
                ('y', models.IntegerField(default=2)),
                ('icon', models.ImageField(default='entity/icons/default.png', upload_to='entity/icons/')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DnD_AI.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_playable', models.BooleanField(default=True)),
                ('name', models.CharField(default='DEFAULT_CHARACTER', max_length=30)),
                ('story', models.CharField(default='DEFAULT_STORY', max_length=1000)),
                ('physical_description', models.CharField(default='Man, tall, white skin, black clothes', max_length=200)),
                ('image', models.ImageField(default='entity/images/default.png', upload_to='entity/images/')),
                ('character_race', models.CharField(default='Human', max_length=30)),
                ('character_class', models.CharField(default='Warrior', max_length=30)),
                ('max_health', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('physical_resistance', models.IntegerField(default=10)),
                ('magical_resistance', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('icon', models.ImageField(default='entity/icons/default.png', upload_to='entity/icons/')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DnD_AI.weapon')),
            ],
        ),
    ]
