# Generated by Django 5.0.1 on 2024-03-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(default='default.png', upload_to='weapon/images/'),
        ),
    ]
