# Generated by Django 5.0.1 on 2024-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
