# Generated by Django 5.0.1 on 2024-03-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0002_weapon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='physical_description',
            field=models.CharField(default='Man, tall, white skin, black clothes', max_length=200),
        ),
        migrations.AddField(
            model_name='monster',
            name='physical_description',
            field=models.CharField(default='Green goblin, small, with no weapon', max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='physical_description',
            field=models.CharField(default='Using his hands', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(default='entity/icons/default.png', upload_to='entity/icons/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='entity/images/default.png', upload_to='entity/images/'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='icon',
            field=models.ImageField(default='entity/icons/default.png', upload_to='entity/icons/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(default='Physical', max_length=15),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(default='weapon/images/default.png', upload_to='weapon/images/'),
        ),
    ]
