# Generated by Django 5.0.1 on 2024-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0002_alter_character_weapon_alter_monster_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
