# Generated by Django 5.0.1 on 2024-03-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0002_weapon_is_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='is_unique',
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
    ]
