# Generated by Django 5.0.1 on 2024-03-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0003_character_physical_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='physical_description',
            field=models.CharField(default="It's using his hands", max_length=100),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(default='Body part', max_length=15),
        ),
    ]
