# Generated by Django 5.0.1 on 2024-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0003_weapon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='range_level_points',
            field=models.IntegerField(default=0),
        ),
    ]
