# Generated by Django 5.0.1 on 2024-03-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0003_remove_weapon_is_unique_weapon_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
