# Generated by Django 5.0.1 on 2024-03-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0006_character_recursiveness_monster_recursiveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
