# Generated by Django 5.0.1 on 2024-03-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0007_alter_character_health_alter_monster_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
