# Generated by Django 5.0.1 on 2024-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0012_monster_is_boss_alter_character_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='entity/icons/'),
        ),
    ]
