# Generated by Django 5.0.1 on 2024-03-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0014_rename_chest_treasure_alter_history_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treasure',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='map/'),
        ),
        migrations.AddField(
            model_name='treasure',
            name='treasure_type',
            field=models.CharField(default='Bag', max_length=30),
        ),
        migrations.AddField(
            model_name='treasure',
            name='weapon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.weapon'),
        ),
    ]
