# Generated by Django 5.0.1 on 2024-03-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0015_treasure_discovered_treasure_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tile_type', models.CharField(default='grass', max_length=30)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
    ]
