# Generated by Django 5.0.1 on 2024-04-19 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0017_alter_character_physical_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Campaign Name', max_length=50)),
                ('size_x', models.IntegerField(default=100)),
                ('size_y', models.IntegerField(default=100)),
                ('initial_context', models.CharField(default='A fantasy world', max_length=3000)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('turns', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('objective_str', models.CharField(default='Defeat the key bosses', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.campaign'),
        ),
        migrations.AddField(
            model_name='history',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.campaign'),
        ),
        migrations.AddField(
            model_name='monster',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.campaign'),
        ),
        migrations.AddField(
            model_name='treasure',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.campaign'),
        ),
    ]
