# Generated by Django 5.0.1 on 2024-04-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0018_campaign_character_campaign_history_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DnD_AI.campaign'),
        ),
    ]
