# Generated by Django 5.0.1 on 2024-05-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DnD_AI', '0022_remove_campaign_initial_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='achievements',
            field=models.CharField(default='.', max_length=2000),
        ),
    ]
